# Generating Machine Learning Datasets from Descriptions

Learn how to generate machine learning datasets based on natural language descriptions. This notebook walks you through defining data structures, generating professional specifications, and creating datasets optimized for training machine learning models using DataWizzAI.

# Initial Setup Guide

## Import Required Packages

In [32]:
# First, import all the necessary packages.
from langchain_openai import ChatOpenAI
from src.DataDefiner import *
from src.DataAugmentor import DataAugmentor
from src.utils.utils import parse_output, try_parse_json, create_json_sample_from_csv, compose_query_message

In [33]:
## Load Environment Variables

from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv())

## Initialize the Language Model

In [34]:
# Please make sure OPENAI_API_KEY is loaded to your environment variables
# Initialize language model
llm = ChatOpenAI(temperature=0.9, model="gpt-3.5-turbo")

# Defining a Data Structure - DescriptionToMLDataset

In [35]:
# Initialize a DataStructureDefiner for the task of defining ML dataset from textual description
pipeline_name = get_pipeline_name('DescriptionToMLDataset')
DataDefinerObj = DataDefiner(llm, pipeline_name=pipeline_name)

In [36]:
# Define the required data structure and view the result structure
dataStructureDescription = "Generate a machine learning dataset for predicting suspicious AML transactions based on features like customer characteristics, transaction characteristics, location, and transactions history characteristics."

In [37]:
# Convert the textual description into a sample of the needed data
dataStructureSample = DataDefinerObj.define_schema_from_description(description=dataStructureDescription)
print(parse_output(dataStructureSample))

> Entering new LLMChain chain...
Prompt after formatting:
You are a system that specializes in generating synthetic data according to user requests.Generate an initial synthetic data sample for the described task (according to the user guidance if provided, or your knowledge otherwise).Provide a sample with 10 number of items; items can be records in a table,records that can potentially be joined in a DB schema, or the equivalent tuples in a JSON format in unstructured text.The task as described by the user: Generate a machine learning dataset for predicting suspicious AML transactions based on features like customer characteristics, transaction characteristics, location, and transactions history characteristics.;The guidance given by an expert: None;Format instructions: Generate Sample synthetic records for tabular data (preferably a single flattened table) that can be used for training a well-performing ML model for the task described in the data description.                Please include any relevant attribute you can think of, as we do not want to miss any feature that the user may find useful.                Format the output as JSON with the dataset name as key.Please make sure you output a valid JSON format, and don't cut it in the middle.Please make sure the output only contains the dataset structure. Omit any text before or after the JSON structure.
Generated Output:

> Finished chain.
{'AML_transaction_dataset':   customer_id  age  gender  income  occupation       location  \
0     Cust001   35    Male   70000    Engineer       New York
1     Cust002   45  Female   90000      Doctor  San Francisco
2     Cust003   30    Male   60000     Teacher        Chicago
3     Cust004   55    Male  100000         CEO    Los Angeles
4     Cust005   40  Female   80000      Lawyer          Miami
5     Cust006   25  Female   50000     Student         Boston
6     Cust007   50    Male   95000  Accountant        Seattle
7     Cust008   35  Female   75000    Engineer        Chicago
8     Cust009   45    Male   90000      Doctor        Houston
9     Cust010   30  Female   60000     Teacher         Dallas

   transaction_amount transaction_type transaction_date transaction_time  \
0                5000    Wire Transfer       2022-01-15         10:30:00
1                8000      Credit Card       2022-02-20         15:45:00
2                3000  Cash Withdrawal       2022-03-10         09:00:00
3               10000  Online Transfer       2022-04-25         12:00:00
4                7000       Debit Card       2022-05-30         18:30:00
5                2000   Mobile Payment       2022-06-12         14:00:00
6                9000     ACH Transfer       2022-07-18         11:45:00
7                6000      Credit Card       2022-08-05         16:30:00
8                8000  Online Transfer       2022-09-15         10:15:00
9                3000       Debit Card       2022-10-20         14:45:00

  source_account destination_account  previous_transactions_count  \
0         Acc101              Acc202                           10
1         Acc203              Acc101                           15
2         Acc104              Acc105                            5
3         Acc106              Acc107                           20
4         Acc108              Acc109                           12
5         Acc110              Acc111                            8
6         Acc112              Acc113                           18
7         Acc114              Acc115                           14
8         Acc116              Acc117                           17
9         Acc118              Acc119                            9

   average_transaction_amount
0                        3000
1                        6000
2                        2000
3                        7000
4                        4000
5                        1500
6                        6500
7                        4500
8                        5500
9                        2500  }

## Optional: create a TaskSpecificationAugmentor

You can augment your data description and turn it into a detailed data requirements specifications by using the TaskSpecificationAugmentor object. This component imitates a data analyst that learns your requirement and translate it into a detailed specification of the needed data and its characteristics.

In [38]:
# Generate professional specifications
task_specifications = TaskSpecificationAugmentor.generate_specifications_from_description(llm, description=dataStructureDescription)

# Print the generated specifications
print("Generated Specifications:")
print(task_specifications)

> Entering new LLMChain chain...
Prompt after formatting:
You are an analyst whose job is to conduct a deep research for a given task, and define the needed data to collect, making sure you don't miss any relevant detail, and gain a deep understanding of the data characteristics.1.  Generate the names of the columns relevant for the description of the user. Use indicative names. Assign each column its type - numerical, categorical, datetime, free text, unique identifier. 2. Revisit each column and complete these details:For numeric columns - describe its distribution, mean and std, min and max values. for numbers and datetimes define the needed format, for categorical columns detail a complete set of categories and its probabilities. For free text columns - specify the mean and std of the text length, For unique identifier columns - specify the format and regEX to follow. For Datetime columns - specify min and max values, as well as the time intervals mean and std values. 3. Important correlations to maintain or other constraints and dependencies. 4. Indicate what fields would be better to be generated by a LLM instead of by a simple code. 5. Indicate if this table is has sequential (transactional) nature.
The task as described by the user: Generate a machine learning dataset for predicting suspicious AML transactions based on features like customer characteristics, transaction characteristics, location, and transactions history characteristics.;Please make sure you output a valid textual description, just guidance, no intro and summary are needed, and don't cut it in the middle.
Generated Extracted Logic:

> Finished chain.
Generated Specifications:
1. Columns relevant for the description of the user:
- User_ID: unique identifier
- Age: numerical
- Gender: categorical
- Income: numerical
- Account_Type: categorical
- Transaction_Amount: numerical
- Transaction_Type: categorical
- Location: free text
- Transaction_Date: datetime
- Previous_Transaction_Amount: numerical

2. Completion of column details:
- Age: distribution, mean=45, std=10, min=20, max=70
- Gender: categories (Male, Female), probabilities (0.6, 0.4)
- Income: distribution, mean=50000, std=20000, min=20000, max=100000
- Account_Type: categories (Savings, Checking), probabilities (0.7, 0.3)
- Transaction_Amount: distribution, mean=1000, std=500, min=100, max=5000
- Transaction_Type: categories (Deposit, Withdrawal), probabilities (0.6, 0.4)
- Location: mean text length=15, std text length=5
- Transaction_Date: format (YYYY-MM-DD HH:MM:SS), min=2022-01-01, max=2022-12-31, time interval mean=1 day, std=0.5 day
- Previous_Transaction_Amount: distribution, mean=800, std=400, min=50, max=3000

3. Important correlations to maintain or other constraints and dependencies:
- Possible correlations between Transaction_Amount and Previous_Transaction_Amount
- Dependencies between Transaction_Type and Transaction_Amount

4. Fields better to be generated by a LLM instead of simple code:
- Prediction of suspicious transactions based on historical data and user characteristics

5. Sequential (transactional) nature of the table:
- The table may have a sequential nature if it includes transaction history characteristics and transaction dates.

In [39]:
# Convert the textual description, aided with the expert specification, into a sample of the needed data
dataStructureSample = DataDefinerObj.define_schema_from_description(description=dataStructureDescription,
                                                                    task_specifications=task_specifications)
print(parse_output(dataStructureSample))

> Entering new LLMChain chain...
Prompt after formatting:
You are a system that specializes in generating synthetic data according to user requests.Generate an initial synthetic data sample for the described task (according to the user guidance if provided, or your knowledge otherwise).Provide a sample with 10 number of items; items can be records in a table,records that can potentially be joined in a DB schema, or the equivalent tuples in a JSON format in unstructured text.The task as described by the user: Generate a machine learning dataset for predicting suspicious AML transactions based on features like customer characteristics, transaction characteristics, location, and transactions history characteristics.;The guidance given by an expert: 1. Columns relevant for the description of the user:
- User_ID: unique identifier
- Age: numerical
- Gender: categorical
- Income: numerical
- Account_Type: categorical
- Transaction_Amount: numerical
- Transaction_Type: categorical
- Location: free text
- Transaction_Date: datetime
- Previous_Transaction_Amount: numerical

2. Completion of column details:
- Age: distribution, mean=45, std=10, min=20, max=70
- Gender: categories (Male, Female), probabilities (0.6, 0.4)
- Income: distribution, mean=50000, std=20000, min=20000, max=100000
- Account_Type: categories (Savings, Checking), probabilities (0.7, 0.3)
- Transaction_Amount: distribution, mean=1000, std=500, min=100, max=5000
- Transaction_Type: categories (Deposit, Withdrawal), probabilities (0.6, 0.4)
- Location: mean text length=15, std text length=5
- Transaction_Date: format (YYYY-MM-DD HH:MM:SS), min=2022-01-01, max=2022-12-31, time interval mean=1 day, std=0.5 day
- Previous_Transaction_Amount: distribution, mean=800, std=400, min=50, max=3000

3. Important correlations to maintain or other constraints and dependencies:
- Possible correlations between Transaction_Amount and Previous_Transaction_Amount
- Dependencies between Transaction_Type and Transaction_Amount

4. Fields better to be generated by a LLM instead of simple code:
- Prediction of suspicious transactions based on historical data and user characteristics

5. Sequential (transactional) nature of the table:
- The table may have a sequential nature if it includes transaction history characteristics and transaction dates.;Format instructions: Generate Sample synthetic records for tabular data (preferably a single flattened table) that can be used for training a well-performing ML model for the task described in the data description.                Please include any relevant attribute you can think of, as we do not want to miss any feature that the user may find useful.                Format the output as JSON with the dataset name as key.Please make sure you output a valid JSON format, and don't cut it in the middle.Please make sure the output only contains the dataset structure. Omit any text before or after the JSON structure.
Generated Output:

> Finished chain.
{'AML_Transactions_Dataset':    User_ID  Age  Gender  Income Account_Type  Transaction_Amount  \
0        1   42    Male   55000      Savings                1200
1        2   55  Female   48000     Checking                 900
2        3   30    Male   70000      Savings                1500
3        4   65  Female   30000      Savings                 700
4        5   38    Male   60000     Checking                1100
5        6   48  Female   40000      Savings                 800
6        7   25    Male   90000     Checking                1300
7        8   50  Female   55000      Savings                1400
8        9   35    Male   75000     Checking                1600
9       10   60    Male   45000     Checking                1000

  Transaction_Type       Location     Transaction_Date  \
0          Deposit       New York  2022-03-15 08:30:00
1       Withdrawal    Los Angeles  2022-07-20 16:45:00
2          Deposit        Chicago  2022-05-10 12:00:00
3       Withdrawal          Miami  2022-11-05 10:20:00
4          Deposit        Seattle  2022-09-30 09:10:00
5          Deposit         Boston  2022-04-25 14:55:00
6       Withdrawal  San Francisco  2022-06-12 11:40:00
7          Deposit         Dallas  2022-08-18 17:30:00
8       Withdrawal        Atlanta  2022-10-22 13:15:00
9          Deposit        Houston  2022-12-10 10:00:00

   Previous_Transaction_Amount
0                          900
1                          800
2                         1100
3                          600
4                         1000
5                          700
6                         1200
7                         1300
8                         1500
9                          900  }

# Generating Data

In [40]:
# First initialize the DataAugmentor object with your chosen language model (llm) and the predefined data structure (dataStructureSample):
DataAugmentorObj = DataAugmentor(llm=llm, structure=dataStructureSample)

## Generate a sample (for output validation)

In [41]:
# You can view a sample of the generated data:
generated_data = DataAugmentorObj.preview_output_sample()
print(generated_data)

> Entering new LLMChain chain...
Prompt after formatting:
You are a system that specializes in generating synthetic data according to user requests.Generate 10 Sample synthetic items(records in a table or the equivalent elements in unstructured text) for the data described below. In the following structure, but with different values.For the following task: Data description: None.Required Structure: {
  "AML_Transactions_Dataset": [
    {
      "User_ID": 1,
      "Age": 42,
      "Gender": "Male",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1200,
      "Transaction_Type": "Deposit",
      "Location": "New York",
      "Transaction_Date": "2022-03-15 08:30:00",
      "Previous_Transaction_Amount": 900
    },
    {
      "User_ID": 2,
      "Age": 55,
      "Gender": "Female",
      "Income": 48000,
      "Account_Type": "Checking",
      "Transaction_Amount": 900,
      "Transaction_Type": "Withdrawal",
      "Location": "Los Angeles",
      "Transaction_Date": "2022-07-20 16:45:00",
      "Previous_Transaction_Amount": 800
    },
    {
      "User_ID": 3,
      "Age": 30,
      "Gender": "Male",
      "Income": 70000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1500,
      "Transaction_Type": "Deposit",
      "Location": "Chicago",
      "Transaction_Date": "2022-05-10 12:00:00",
      "Previous_Transaction_Amount": 1100
    },
    {
      "User_ID": 4,
      "Age": 65,
      "Gender": "Female",
      "Income": 30000,
      "Account_Type": "Savings",
      "Transaction_Amount": 700,
      "Transaction_Type": "Withdrawal",
      "Location": "Miami",
      "Transaction_Date": "2022-11-05 10:20:00",
      "Previous_Transaction_Amount": 600
    },
    {
      "User_ID": 5,
      "Age": 38,
      "Gender": "Male",
      "Income": 60000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1100,
      "Transaction_Type": "Deposit",
      "Location": "Seattle",
      "Transaction_Date": "2022-09-30 09:10:00",
      "Previous_Transaction_Amount": 1000
    },
    {
      "User_ID": 6,
      "Age": 48,
      "Gender": "Female",
      "Income": 40000,
      "Account_Type": "Savings",
      "Transaction_Amount": 800,
      "Transaction_Type": "Deposit",
      "Location": "Boston",
      "Transaction_Date": "2022-04-25 14:55:00",
      "Previous_Transaction_Amount": 700
    },
    {
      "User_ID": 7,
      "Age": 25,
      "Gender": "Male",
      "Income": 90000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1300,
      "Transaction_Type": "Withdrawal",
      "Location": "San Francisco",
      "Transaction_Date": "2022-06-12 11:40:00",
      "Previous_Transaction_Amount": 1200
    },
    {
      "User_ID": 8,
      "Age": 50,
      "Gender": "Female",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1400,
      "Transaction_Type": "Deposit",
      "Location": "Dallas",
      "Transaction_Date": "2022-08-18 17:30:00",
      "Previous_Transaction_Amount": 1300
    },
    {
      "User_ID": 9,
      "Age": 35,
      "Gender": "Male",
      "Income": 75000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1600,
      "Transaction_Type": "Withdrawal",
      "Location": "Atlanta",
      "Transaction_Date": "2022-10-22 13:15:00",
      "Previous_Transaction_Amount": 1500
    },
    {
      "User_ID": 10,
      "Age": 60,
      "Gender": "Male",
      "Income": 45000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1000,
      "Transaction_Type": "Deposit",
      "Location": "Houston",
      "Transaction_Date": "2022-12-10 10:00:00",
      "Previous_Transaction_Amount": 900
    }
  ]
}.The previous generated batch (maintain sequential patterns if needed): unknown.Add Randomness: 0.33173733858069954.It is critical that you don't repeat the same values every time you get this prompt.
Generated Output:

> Finished chain.
{'AML_Transactions_Dataset':    User_ID  Age  Gender  Income Account_Type  Transaction_Amount  \
0       11   45  Female   52000     Checking                1250
1       12   32    Male   68000      Savings                1550
2       13   70    Male   32000     Checking                 750
3       14   40  Female   62000      Savings                1150
4       15   33    Male   58000     Checking                1350
5       16   53  Female   42000      Savings                 850
6       17   28    Male   94000     Checking                1370
7       18   52  Female   57000      Savings                1470
8       19   37    Male   79000     Checking                1670
9       20   62    Male   47000     Checking                1050

  Transaction_Type      Location     Transaction_Date  \
0          Deposit       Phoenix  2022-03-25 09:45:00
1          Deposit        Denver  2022-07-29 18:00:00
2       Withdrawal     Las Vegas  2022-05-15 13:30:00
3       Withdrawal       Orlando  2022-11-10 11:00:00
4          Deposit     San Diego  2022-09-05 10:20:00
5          Deposit      Portland  2022-04-30 15:55:00
6       Withdrawal        Austin  2022-06-17 12:40:00
7          Deposit     Nashville  2022-08-23 18:30:00
8       Withdrawal       Detroit  2022-10-27 14:15:00
9          Deposit  Philadelphia  2022-12-15 11:00:00

   Previous_Transaction_Amount
0                          950
1                         1150
2                          650
3                          850
4                         1050
5                          750
6                         1270
7                         1370
8                         1570
9                          950  }

## Optional: query/filter the data structure to control the generated content

In [42]:
# You can also add queries and filters to guide the generated contents:
region = 'France'
language = 'French'
query = "Only 40 years old customers or older."

generated_data = DataAugmentorObj.preview_output_sample(query=query, region=region, language=language)
print(generated_data)

> Entering new LLMChain chain...
Prompt after formatting:
You are a system that specializes in generating synthetic data according to user requests.Generate 10 Sample synthetic items(records in a table or the equivalent elements in unstructured text) for the data described below. In the following structure, but with different values.For the following task: Data description: Only 40 years old customers or older. ; The required region: France ; All texts should be translated to French language..Required Structure: {
  "AML_Transactions_Dataset": [
    {
      "User_ID": 1,
      "Age": 42,
      "Gender": "Male",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1200,
      "Transaction_Type": "Deposit",
      "Location": "New York",
      "Transaction_Date": "2022-03-15 08:30:00",
      "Previous_Transaction_Amount": 900
    },
    {
      "User_ID": 2,
      "Age": 55,
      "Gender": "Female",
      "Income": 48000,
      "Account_Type": "Checking",
      "Transaction_Amount": 900,
      "Transaction_Type": "Withdrawal",
      "Location": "Los Angeles",
      "Transaction_Date": "2022-07-20 16:45:00",
      "Previous_Transaction_Amount": 800
    },
    {
      "User_ID": 3,
      "Age": 30,
      "Gender": "Male",
      "Income": 70000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1500,
      "Transaction_Type": "Deposit",
      "Location": "Chicago",
      "Transaction_Date": "2022-05-10 12:00:00",
      "Previous_Transaction_Amount": 1100
    },
    {
      "User_ID": 4,
      "Age": 65,
      "Gender": "Female",
      "Income": 30000,
      "Account_Type": "Savings",
      "Transaction_Amount": 700,
      "Transaction_Type": "Withdrawal",
      "Location": "Miami",
      "Transaction_Date": "2022-11-05 10:20:00",
      "Previous_Transaction_Amount": 600
    },
    {
      "User_ID": 5,
      "Age": 38,
      "Gender": "Male",
      "Income": 60000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1100,
      "Transaction_Type": "Deposit",
      "Location": "Seattle",
      "Transaction_Date": "2022-09-30 09:10:00",
      "Previous_Transaction_Amount": 1000
    },
    {
      "User_ID": 6,
      "Age": 48,
      "Gender": "Female",
      "Income": 40000,
      "Account_Type": "Savings",
      "Transaction_Amount": 800,
      "Transaction_Type": "Deposit",
      "Location": "Boston",
      "Transaction_Date": "2022-04-25 14:55:00",
      "Previous_Transaction_Amount": 700
    },
    {
      "User_ID": 7,
      "Age": 25,
      "Gender": "Male",
      "Income": 90000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1300,
      "Transaction_Type": "Withdrawal",
      "Location": "San Francisco",
      "Transaction_Date": "2022-06-12 11:40:00",
      "Previous_Transaction_Amount": 1200
    },
    {
      "User_ID": 8,
      "Age": 50,
      "Gender": "Female",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1400,
      "Transaction_Type": "Deposit",
      "Location": "Dallas",
      "Transaction_Date": "2022-08-18 17:30:00",
      "Previous_Transaction_Amount": 1300
    },
    {
      "User_ID": 9,
      "Age": 35,
      "Gender": "Male",
      "Income": 75000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1600,
      "Transaction_Type": "Withdrawal",
      "Location": "Atlanta",
      "Transaction_Date": "2022-10-22 13:15:00",
      "Previous_Transaction_Amount": 1500
    },
    {
      "User_ID": 10,
      "Age": 60,
      "Gender": "Male",
      "Income": 45000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1000,
      "Transaction_Type": "Deposit",
      "Location": "Houston",
      "Transaction_Date": "2022-12-10 10:00:00",
      "Previous_Transaction_Amount": 900
    }
  ]
}.The previous generated batch (maintain sequential patterns if needed): {
  "AML_Transactions_Dataset": [
    {
      "User_ID": 11,
      "Age": 45,
      "Gender": "Female",
      "Income": 52000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1250,
      "Transaction_Type": "Deposit",
      "Location": "Phoenix",
      "Transaction_Date": "2022-03-25 09:45:00",
      "Previous_Transaction_Amount": 950
    },
    {
      "User_ID": 12,
      "Age": 32,
      "Gender": "Male",
      "Income": 68000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1550,
      "Transaction_Type": "Deposit",
      "Location": "Denver",
      "Transaction_Date": "2022-07-29 18:00:00",
      "Previous_Transaction_Amount": 1150
    },
    {
      "User_ID": 13,
      "Age": 70,
      "Gender": "Male",
      "Income": 32000,
      "Account_Type": "Checking",
      "Transaction_Amount": 750,
      "Transaction_Type": "Withdrawal",
      "Location": "Las Vegas",
      "Transaction_Date": "2022-05-15 13:30:00",
      "Previous_Transaction_Amount": 650
    },
    {
      "User_ID": 14,
      "Age": 40,
      "Gender": "Female",
      "Income": 62000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1150,
      "Transaction_Type": "Withdrawal",
      "Location": "Orlando",
      "Transaction_Date": "2022-11-10 11:00:00",
      "Previous_Transaction_Amount": 850
    },
    {
      "User_ID": 15,
      "Age": 33,
      "Gender": "Male",
      "Income": 58000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1350,
      "Transaction_Type": "Deposit",
      "Location": "San Diego",
      "Transaction_Date": "2022-09-05 10:20:00",
      "Previous_Transaction_Amount": 1050
    },
    {
      "User_ID": 16,
      "Age": 53,
      "Gender": "Female",
      "Income": 42000,
      "Account_Type": "Savings",
      "Transaction_Amount": 850,
      "Transaction_Type": "Deposit",
      "Location": "Portland",
      "Transaction_Date": "2022-04-30 15:55:00",
      "Previous_Transaction_Amount": 750
    },
    {
      "User_ID": 17,
      "Age": 28,
      "Gender": "Male",
      "Income": 94000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1370,
      "Transaction_Type": "Withdrawal",
      "Location": "Austin",
      "Transaction_Date": "2022-06-17 12:40:00",
      "Previous_Transaction_Amount": 1270
    },
    {
      "User_ID": 18,
      "Age": 52,
      "Gender": "Female",
      "Income": 57000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1470,
      "Transaction_Type": "Deposit",
      "Location": "Nashville",
      "Transaction_Date": "2022-08-23 18:30:00",
      "Previous_Transaction_Amount": 1370
    },
    {
      "User_ID": 19,
      "Age": 37,
      "Gender": "Male",
      "Income": 79000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1670,
      "Transaction_Type": "Withdrawal",
      "Location": "Detroit",
      "Transaction_Date": "2022-10-27 14:15:00",
      "Previous_Transaction_Amount": 1570
    },
    {
      "User_ID": 20,
      "Age": 62,
      "Gender": "Male",
      "Income": 47000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1050,
      "Transaction_Type": "Deposit",
      "Location": "Philadelphia",
      "Transaction_Date": "2022-12-15 11:00:00",
      "Previous_Transaction_Amount": 950
    }
  ]
}.Add Randomness: 0.15472036586147953.It is critical that you don't repeat the same values every time you get this prompt.
Generated Output:

> Finished chain.
{'AML_Transactions_Dataset':    User_ID  Age  Gender  Income Account_Type  Transaction_Amount  \
0       21   43    Male   56000      Savings                1220
1       22   66  Female   31000      Savings                 720
2       23   42    Male   69000     Checking                1520
3       24   63  Female   33000      Savings                 770
4       25   37    Male   63000     Checking                1120
5       26   49  Female   41000      Savings                 820
6       27   32    Male   92000     Checking                1320
7       28   51  Female   56000      Savings                1420
8       29   36    Male   80000     Checking                1620
9       30   65    Male   46000     Checking                1020

  Transaction_Type     Location     Transaction_Date  \
0          Deposit        Paris  2022-04-05 09:30:00
1       Withdrawal    Marseille  2022-11-20 10:45:00
2          Deposit         Lyon  2022-03-10 11:00:00
3       Withdrawal         Nice  2022-09-05 08:10:00
4          Deposit   Strasbourg  2022-06-30 08:00:00
5          Deposit     Toulouse  2022-01-25 13:55:00
6       Withdrawal     Bordeaux  2022-05-12 12:40:00
7          Deposit        Lille  2022-08-18 18:30:00
8       Withdrawal       Nantes  2022-10-22 14:15:00
9          Deposit  Montpellier  2022-12-10 11:00:00

   Previous_Transaction_Amount
0                          920
1                          620
2                         1120
3                          670
4                         1020
5                          720
6                         1220
7                         1320
8                         1520
9                          920  }

In [43]:
# If you used TaskSpecificationAugmentor for defining this structure, and you wish to add queries and filters to guide the content generate, it will be a good idea to revisit the expert specifications to adjust it to the user query and guidance while maintaining the external wisdom:
full_query = compose_query_message(query=query, region=region, language=language)
updated_task_specifications = TaskSpecificationAugmentor.refine_specifications_by_description(llm=llm,
description=full_query,previous_task_specification=task_specifications)

generated_data = DataAugmentorObj.preview_output_sample(query=query, region=region, language=language,
                                                        task_specifications=updated_task_specifications)
print(generated_data)

> Entering new LLMChain chain...
Prompt after formatting:
You are an analyst whose job is to conduct a deep research for a given task, and define the needed data to collect, making sure you don't miss any relevant detail, and gain a deep understanding of the data characteristics.You already gave instructions for the needed data (see Previous Task Specifications), but now the user asks a content refinement (see User Query). Please revisit the columns distributions, and descriptive statistics and update those that have changed due to the user query.
The User Query: Data description: Only 40 years old customers or older. ; The required region: France ; All texts should be translated to French language.;
Your Previous Task Specifications: 1. Columns relevant for the description of the user:
- User_ID: unique identifier
- Age: numerical
- Gender: categorical
- Income: numerical
- Account_Type: categorical
- Transaction_Amount: numerical
- Transaction_Type: categorical
- Location: free text
- Transaction_Date: datetime
- Previous_Transaction_Amount: numerical

2. Completion of column details:
- Age: distribution, mean=45, std=10, min=20, max=70
- Gender: categories (Male, Female), probabilities (0.6, 0.4)
- Income: distribution, mean=50000, std=20000, min=20000, max=100000
- Account_Type: categories (Savings, Checking), probabilities (0.7, 0.3)
- Transaction_Amount: distribution, mean=1000, std=500, min=100, max=5000
- Transaction_Type: categories (Deposit, Withdrawal), probabilities (0.6, 0.4)
- Location: mean text length=15, std text length=5
- Transaction_Date: format (YYYY-MM-DD HH:MM:SS), min=2022-01-01, max=2022-12-31, time interval mean=1 day, std=0.5 day
- Previous_Transaction_Amount: distribution, mean=800, std=400, min=50, max=3000

3. Important correlations to maintain or other constraints and dependencies:
- Possible correlations between Transaction_Amount and Previous_Transaction_Amount
- Dependencies between Transaction_Type and Transaction_Amount

4. Fields better to be generated by a LLM instead of simple code:
- Prediction of suspicious transactions based on historical data and user characteristics

5. Sequential (transactional) nature of the table:
- The table may have a sequential nature if it includes transaction history characteristics and transaction dates.;Please make sure you output a valid textual description, just guidance, no intro and summary are needed, and don't cut it in the middle.
Generated Extracted Logic:

> Finished chain.


> Entering new LLMChain chain...
Prompt after formatting:
You are a system that specializes in generating synthetic data according to user requests.Generate 10 Sample synthetic items(records in a table or the equivalent elements in unstructured text) for the data described below. In the following structure, but with different values.For the following task: Data description: Only 40 years old customers or older. ; The required region: France ; All texts should be translated to French language. ; The guidance given by an expert: - Age: distribution, mean=50, std=8, min=40, max=70
- Gender: categories (Homme, Femme), probabilities (0.6, 0.4)
- Income: distribution, mean=55000, std=25000, min=25000, max=110000
- Account_Type: categories (Épargne, Chèque), probabilities (0.7, 0.3)
- Transaction_Amount: distribution, mean=1200, std=600, min=200, max=6000
- Transaction_Type: categories (Dépôt, Retrait), probabilities (0.6, 0.4)
- Location: mean text length=15, std text length=5
- Transaction_Date: format (AAAA-MM-JJ HH:MM:SS), min=2022-01-01, max=2022-12-31, time interval mean=1 day, std=0.5 day
- Previous_Transaction_Amount: distribution, mean=850, std=450, min=100, max=3200..Required Structure: {
  "AML_Transactions_Dataset": [
    {
      "User_ID": 1,
      "Age": 42,
      "Gender": "Male",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1200,
      "Transaction_Type": "Deposit",
      "Location": "New York",
      "Transaction_Date": "2022-03-15 08:30:00",
      "Previous_Transaction_Amount": 900
    },
    {
      "User_ID": 2,
      "Age": 55,
      "Gender": "Female",
      "Income": 48000,
      "Account_Type": "Checking",
      "Transaction_Amount": 900,
      "Transaction_Type": "Withdrawal",
      "Location": "Los Angeles",
      "Transaction_Date": "2022-07-20 16:45:00",
      "Previous_Transaction_Amount": 800
    },
    {
      "User_ID": 3,
      "Age": 30,
      "Gender": "Male",
      "Income": 70000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1500,
      "Transaction_Type": "Deposit",
      "Location": "Chicago",
      "Transaction_Date": "2022-05-10 12:00:00",
      "Previous_Transaction_Amount": 1100
    },
    {
      "User_ID": 4,
      "Age": 65,
      "Gender": "Female",
      "Income": 30000,
      "Account_Type": "Savings",
      "Transaction_Amount": 700,
      "Transaction_Type": "Withdrawal",
      "Location": "Miami",
      "Transaction_Date": "2022-11-05 10:20:00",
      "Previous_Transaction_Amount": 600
    },
    {
      "User_ID": 5,
      "Age": 38,
      "Gender": "Male",
      "Income": 60000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1100,
      "Transaction_Type": "Deposit",
      "Location": "Seattle",
      "Transaction_Date": "2022-09-30 09:10:00",
      "Previous_Transaction_Amount": 1000
    },
    {
      "User_ID": 6,
      "Age": 48,
      "Gender": "Female",
      "Income": 40000,
      "Account_Type": "Savings",
      "Transaction_Amount": 800,
      "Transaction_Type": "Deposit",
      "Location": "Boston",
      "Transaction_Date": "2022-04-25 14:55:00",
      "Previous_Transaction_Amount": 700
    },
    {
      "User_ID": 7,
      "Age": 25,
      "Gender": "Male",
      "Income": 90000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1300,
      "Transaction_Type": "Withdrawal",
      "Location": "San Francisco",
      "Transaction_Date": "2022-06-12 11:40:00",
      "Previous_Transaction_Amount": 1200
    },
    {
      "User_ID": 8,
      "Age": 50,
      "Gender": "Female",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1400,
      "Transaction_Type": "Deposit",
      "Location": "Dallas",
      "Transaction_Date": "2022-08-18 17:30:00",
      "Previous_Transaction_Amount": 1300
    },
    {
      "User_ID": 9,
      "Age": 35,
      "Gender": "Male",
      "Income": 75000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1600,
      "Transaction_Type": "Withdrawal",
      "Location": "Atlanta",
      "Transaction_Date": "2022-10-22 13:15:00",
      "Previous_Transaction_Amount": 1500
    },
    {
      "User_ID": 10,
      "Age": 60,
      "Gender": "Male",
      "Income": 45000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1000,
      "Transaction_Type": "Deposit",
      "Location": "Houston",
      "Transaction_Date": "2022-12-10 10:00:00",
      "Previous_Transaction_Amount": 900
    }
  ]
}.The previous generated batch (maintain sequential patterns if needed): {
  "AML_Transactions_Dataset": [
    {
      "User_ID": 21,
      "Age": 43,
      "Gender": "Male",
      "Income": 56000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1220,
      "Transaction_Type": "Deposit",
      "Location": "Paris",
      "Transaction_Date": "2022-04-05 09:30:00",
      "Previous_Transaction_Amount": 920
    },
    {
      "User_ID": 22,
      "Age": 66,
      "Gender": "Female",
      "Income": 31000,
      "Account_Type": "Savings",
      "Transaction_Amount": 720,
      "Transaction_Type": "Withdrawal",
      "Location": "Marseille",
      "Transaction_Date": "2022-11-20 10:45:00",
      "Previous_Transaction_Amount": 620
    },
    {
      "User_ID": 23,
      "Age": 42,
      "Gender": "Male",
      "Income": 69000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1520,
      "Transaction_Type": "Deposit",
      "Location": "Lyon",
      "Transaction_Date": "2022-03-10 11:00:00",
      "Previous_Transaction_Amount": 1120
    },
    {
      "User_ID": 24,
      "Age": 63,
      "Gender": "Female",
      "Income": 33000,
      "Account_Type": "Savings",
      "Transaction_Amount": 770,
      "Transaction_Type": "Withdrawal",
      "Location": "Nice",
      "Transaction_Date": "2022-09-05 08:10:00",
      "Previous_Transaction_Amount": 670
    },
    {
      "User_ID": 25,
      "Age": 37,
      "Gender": "Male",
      "Income": 63000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1120,
      "Transaction_Type": "Deposit",
      "Location": "Strasbourg",
      "Transaction_Date": "2022-06-30 08:00:00",
      "Previous_Transaction_Amount": 1020
    },
    {
      "User_ID": 26,
      "Age": 49,
      "Gender": "Female",
      "Income": 41000,
      "Account_Type": "Savings",
      "Transaction_Amount": 820,
      "Transaction_Type": "Deposit",
      "Location": "Toulouse",
      "Transaction_Date": "2022-01-25 13:55:00",
      "Previous_Transaction_Amount": 720
    },
    {
      "User_ID": 27,
      "Age": 32,
      "Gender": "Male",
      "Income": 92000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1320,
      "Transaction_Type": "Withdrawal",
      "Location": "Bordeaux",
      "Transaction_Date": "2022-05-12 12:40:00",
      "Previous_Transaction_Amount": 1220
    },
    {
      "User_ID": 28,
      "Age": 51,
      "Gender": "Female",
      "Income": 56000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1420,
      "Transaction_Type": "Deposit",
      "Location": "Lille",
      "Transaction_Date": "2022-08-18 18:30:00",
      "Previous_Transaction_Amount": 1320
    },
    {
      "User_ID": 29,
      "Age": 36,
      "Gender": "Male",
      "Income": 80000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1620,
      "Transaction_Type": "Withdrawal",
      "Location": "Nantes",
      "Transaction_Date": "2022-10-22 14:15:00",
      "Previous_Transaction_Amount": 1520
    },
    {
      "User_ID": 30,
      "Age": 65,
      "Gender": "Male",
      "Income": 46000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1020,
      "Transaction_Type": "Deposit",
      "Location": "Montpellier",
      "Transaction_Date": "2022-12-10 11:00:00",
      "Previous_Transaction_Amount": 920
    }
  ]
}.Add Randomness: 0.03853237405722121.It is critical that you don't repeat the same values every time you get this prompt.
Generated Output:

> Finished chain.
{'AML_Transactions_Dataset':    User_ID  Age Gender  Income Account_Type  Transaction_Amount  \
0       31   41  Homme   62000      Épargne                1250
1       32   54  Femme   51000       Chèque                 950
2       33   47  Homme   68000      Épargne                1550
3       34   69  Femme   28000      Épargne                 750
4       35   43  Homme   64000       Chèque                1150
5       36   45  Femme   44000      Épargne                 850
6       37   46  Homme   71000       Chèque                1300
7       38   39  Femme   68000      Épargne                1450
8       39   44  Homme   67000       Chèque                1600
9       40   68  Femme   29000       Chèque                 850

  Transaction_Type     Location     Transaction_Date  \
0            Dépôt     Bordeaux  2022-03-20 09:35:00
1          Retrait         Nice  2022-07-25 17:00:00
2            Dépôt         Lyon  2022-05-15 12:15:00
3          Retrait    Marseille  2022-11-10 09:20:00
4            Dépôt        Paris  2022-09-05 08:10:00
5            Dépôt        Lille  2022-04-30 15:55:00
6          Retrait     Toulouse  2022-06-15 10:40:00
7            Dépôt       Nantes  2022-08-20 19:30:00
8            Dépôt  Montpellier  2022-10-25 11:15:00
9          Retrait   Strasbourg  2022-12-20 10:00:00

   Previous_Transaction_Amount
0                          950
1                          850
2                         1150
3                          650
4                         1050
5                          750
6                         1200
7                         1350
8                         1500
9                          750  }

## Generating Full Output

To generate the full dataset, use the generate_data method. Specify your query (if any), optionaly the region and language, and the number of records you wish to generate.

In [44]:
# Without expert specifications
generated_data = DataAugmentorObj.generate_data( query=query, region=region, language=language, num_records=15) 

# With expert specifications
#generated_data = DataAugmentorObj.generate_data( query=query, region=region, language=language, task_specifications=updated_task_specifications, num_records=15)

> Entering new LLMChain chain...
Prompt after formatting:
You are a system that specializes in generating synthetic data according to user requests.Generate 10 Sample synthetic items(records in a table or the equivalent elements in unstructured text) for the data described below. In the following structure, but with different values.For the following task: Data description: Only 40 years old customers or older. ; The required region: France ; All texts should be translated to French language..Required Structure: {
  "AML_Transactions_Dataset": [
    {
      "User_ID": 1,
      "Age": 42,
      "Gender": "Male",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1200,
      "Transaction_Type": "Deposit",
      "Location": "New York",
      "Transaction_Date": "2022-03-15 08:30:00",
      "Previous_Transaction_Amount": 900
    },
    {
      "User_ID": 2,
      "Age": 55,
      "Gender": "Female",
      "Income": 48000,
      "Account_Type": "Checking",
      "Transaction_Amount": 900,
      "Transaction_Type": "Withdrawal",
      "Location": "Los Angeles",
      "Transaction_Date": "2022-07-20 16:45:00",
      "Previous_Transaction_Amount": 800
    },
    {
      "User_ID": 3,
      "Age": 30,
      "Gender": "Male",
      "Income": 70000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1500,
      "Transaction_Type": "Deposit",
      "Location": "Chicago",
      "Transaction_Date": "2022-05-10 12:00:00",
      "Previous_Transaction_Amount": 1100
    },
    {
      "User_ID": 4,
      "Age": 65,
      "Gender": "Female",
      "Income": 30000,
      "Account_Type": "Savings",
      "Transaction_Amount": 700,
      "Transaction_Type": "Withdrawal",
      "Location": "Miami",
      "Transaction_Date": "2022-11-05 10:20:00",
      "Previous_Transaction_Amount": 600
    },
    {
      "User_ID": 5,
      "Age": 38,
      "Gender": "Male",
      "Income": 60000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1100,
      "Transaction_Type": "Deposit",
      "Location": "Seattle",
      "Transaction_Date": "2022-09-30 09:10:00",
      "Previous_Transaction_Amount": 1000
    },
    {
      "User_ID": 6,
      "Age": 48,
      "Gender": "Female",
      "Income": 40000,
      "Account_Type": "Savings",
      "Transaction_Amount": 800,
      "Transaction_Type": "Deposit",
      "Location": "Boston",
      "Transaction_Date": "2022-04-25 14:55:00",
      "Previous_Transaction_Amount": 700
    },
    {
      "User_ID": 7,
      "Age": 25,
      "Gender": "Male",
      "Income": 90000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1300,
      "Transaction_Type": "Withdrawal",
      "Location": "San Francisco",
      "Transaction_Date": "2022-06-12 11:40:00",
      "Previous_Transaction_Amount": 1200
    },
    {
      "User_ID": 8,
      "Age": 50,
      "Gender": "Female",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1400,
      "Transaction_Type": "Deposit",
      "Location": "Dallas",
      "Transaction_Date": "2022-08-18 17:30:00",
      "Previous_Transaction_Amount": 1300
    },
    {
      "User_ID": 9,
      "Age": 35,
      "Gender": "Male",
      "Income": 75000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1600,
      "Transaction_Type": "Withdrawal",
      "Location": "Atlanta",
      "Transaction_Date": "2022-10-22 13:15:00",
      "Previous_Transaction_Amount": 1500
    },
    {
      "User_ID": 10,
      "Age": 60,
      "Gender": "Male",
      "Income": 45000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1000,
      "Transaction_Type": "Deposit",
      "Location": "Houston",
      "Transaction_Date": "2022-12-10 10:00:00",
      "Previous_Transaction_Amount": 900
    }
  ]
}.The previous generated batch (maintain sequential patterns if needed): {
  "AML_Transactions_Dataset": [
    {
      "User_ID": 31,
      "Age": 41,
      "Gender": "Homme",
      "Income": 62000,
      "Account_Type": "Épargne",
      "Transaction_Amount": 1250,
      "Transaction_Type": "Dépôt",
      "Location": "Bordeaux",
      "Transaction_Date": "2022-03-20 09:35:00",
      "Previous_Transaction_Amount": 950
    },
    {
      "User_ID": 32,
      "Age": 54,
      "Gender": "Femme",
      "Income": 51000,
      "Account_Type": "Chèque",
      "Transaction_Amount": 950,
      "Transaction_Type": "Retrait",
      "Location": "Nice",
      "Transaction_Date": "2022-07-25 17:00:00",
      "Previous_Transaction_Amount": 850
    },
    {
      "User_ID": 33,
      "Age": 47,
      "Gender": "Homme",
      "Income": 68000,
      "Account_Type": "Épargne",
      "Transaction_Amount": 1550,
      "Transaction_Type": "Dépôt",
      "Location": "Lyon",
      "Transaction_Date": "2022-05-15 12:15:00",
      "Previous_Transaction_Amount": 1150
    },
    {
      "User_ID": 34,
      "Age": 69,
      "Gender": "Femme",
      "Income": 28000,
      "Account_Type": "Épargne",
      "Transaction_Amount": 750,
      "Transaction_Type": "Retrait",
      "Location": "Marseille",
      "Transaction_Date": "2022-11-10 09:20:00",
      "Previous_Transaction_Amount": 650
    },
    {
      "User_ID": 35,
      "Age": 43,
      "Gender": "Homme",
      "Income": 64000,
      "Account_Type": "Chèque",
      "Transaction_Amount": 1150,
      "Transaction_Type": "Dépôt",
      "Location": "Paris",
      "Transaction_Date": "2022-09-05 08:10:00",
      "Previous_Transaction_Amount": 1050
    },
    {
      "User_ID": 36,
      "Age": 45,
      "Gender": "Femme",
      "Income": 44000,
      "Account_Type": "Épargne",
      "Transaction_Amount": 850,
      "Transaction_Type": "Dépôt",
      "Location": "Lille",
      "Transaction_Date": "2022-04-30 15:55:00",
      "Previous_Transaction_Amount": 750
    },
    {
      "User_ID": 37,
      "Age": 46,
      "Gender": "Homme",
      "Income": 71000,
      "Account_Type": "Chèque",
      "Transaction_Amount": 1300,
      "Transaction_Type": "Retrait",
      "Location": "Toulouse",
      "Transaction_Date": "2022-06-15 10:40:00",
      "Previous_Transaction_Amount": 1200
    },
    {
      "User_ID": 38,
      "Age": 39,
      "Gender": "Femme",
      "Income": 68000,
      "Account_Type": "Épargne",
      "Transaction_Amount": 1450,
      "Transaction_Type": "Dépôt",
      "Location": "Nantes",
      "Transaction_Date": "2022-08-20 19:30:00",
      "Previous_Transaction_Amount": 1350
    },
    {
      "User_ID": 39,
      "Age": 44,
      "Gender": "Homme",
      "Income": 67000,
      "Account_Type": "Chèque",
      "Transaction_Amount": 1600,
      "Transaction_Type": "Dépôt",
      "Location": "Montpellier",
      "Transaction_Date": "2022-10-25 11:15:00",
      "Previous_Transaction_Amount": 1500
    },
    {
      "User_ID": 40,
      "Age": 68,
      "Gender": "Femme",
      "Income": 29000,
      "Account_Type": "Chèque",
      "Transaction_Amount": 850,
      "Transaction_Type": "Retrait",
      "Location": "Strasbourg",
      "Transaction_Date": "2022-12-20 10:00:00",
      "Previous_Transaction_Amount": 750
    }
  ]
}.Add Randomness: 0.07847996165286275.It is critical that you don't repeat the same values every time you get this prompt.
Generated Output:

> Finished chain.


> Entering new LLMChain chain...
Prompt after formatting:
You are a system that specializes in generating synthetic data according to user requests.Generate 10 Sample synthetic items(records in a table or the equivalent elements in unstructured text) for the data described below. In the following structure, but with different values.For the following task: Data description: Only 40 years old customers or older. ; The required region: France ; All texts should be translated to French language..Required Structure: {
  "AML_Transactions_Dataset": [
    {
      "User_ID": 1,
      "Age": 42,
      "Gender": "Male",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1200,
      "Transaction_Type": "Deposit",
      "Location": "New York",
      "Transaction_Date": "2022-03-15 08:30:00",
      "Previous_Transaction_Amount": 900
    },
    {
      "User_ID": 2,
      "Age": 55,
      "Gender": "Female",
      "Income": 48000,
      "Account_Type": "Checking",
      "Transaction_Amount": 900,
      "Transaction_Type": "Withdrawal",
      "Location": "Los Angeles",
      "Transaction_Date": "2022-07-20 16:45:00",
      "Previous_Transaction_Amount": 800
    },
    {
      "User_ID": 3,
      "Age": 30,
      "Gender": "Male",
      "Income": 70000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1500,
      "Transaction_Type": "Deposit",
      "Location": "Chicago",
      "Transaction_Date": "2022-05-10 12:00:00",
      "Previous_Transaction_Amount": 1100
    },
    {
      "User_ID": 4,
      "Age": 65,
      "Gender": "Female",
      "Income": 30000,
      "Account_Type": "Savings",
      "Transaction_Amount": 700,
      "Transaction_Type": "Withdrawal",
      "Location": "Miami",
      "Transaction_Date": "2022-11-05 10:20:00",
      "Previous_Transaction_Amount": 600
    },
    {
      "User_ID": 5,
      "Age": 38,
      "Gender": "Male",
      "Income": 60000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1100,
      "Transaction_Type": "Deposit",
      "Location": "Seattle",
      "Transaction_Date": "2022-09-30 09:10:00",
      "Previous_Transaction_Amount": 1000
    },
    {
      "User_ID": 6,
      "Age": 48,
      "Gender": "Female",
      "Income": 40000,
      "Account_Type": "Savings",
      "Transaction_Amount": 800,
      "Transaction_Type": "Deposit",
      "Location": "Boston",
      "Transaction_Date": "2022-04-25 14:55:00",
      "Previous_Transaction_Amount": 700
    },
    {
      "User_ID": 7,
      "Age": 25,
      "Gender": "Male",
      "Income": 90000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1300,
      "Transaction_Type": "Withdrawal",
      "Location": "San Francisco",
      "Transaction_Date": "2022-06-12 11:40:00",
      "Previous_Transaction_Amount": 1200
    },
    {
      "User_ID": 8,
      "Age": 50,
      "Gender": "Female",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1400,
      "Transaction_Type": "Deposit",
      "Location": "Dallas",
      "Transaction_Date": "2022-08-18 17:30:00",
      "Previous_Transaction_Amount": 1300
    },
    {
      "User_ID": 9,
      "Age": 35,
      "Gender": "Male",
      "Income": 75000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1600,
      "Transaction_Type": "Withdrawal",
      "Location": "Atlanta",
      "Transaction_Date": "2022-10-22 13:15:00",
      "Previous_Transaction_Amount": 1500
    },
    {
      "User_ID": 10,
      "Age": 60,
      "Gender": "Male",
      "Income": 45000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1000,
      "Transaction_Type": "Deposit",
      "Location": "Houston",
      "Transaction_Date": "2022-12-10 10:00:00",
      "Previous_Transaction_Amount": 900
    }
  ]
}.The previous generated batch (maintain sequential patterns if needed): {
  "AML_Transactions_Dataset": [
    {
      "User_ID": 41,
      "Age": 48,
      "Gender": "Homme",
      "Income": 59000,
      "Account_Type": "Épargne",
      "Transaction_Amount": 1175,
      "Transaction_Type": "Dépôt",
      "Location": "Toulouse",
      "Transaction_Date": "2022-03-23 09:45:00",
      "Previous_Transaction_Amount": 925
    },
    {
      "User_ID": 42,
      "Age": 55,
      "Gender": "Femme",
      "Income": 48000,
      "Account_Type": "Chèque",
      "Transaction_Amount": 875,
      "Transaction_Type": "Retrait",
      "Location": "Nice",
      "Transaction_Date": "2022-07-28 17:15:00",
      "Previous_Transaction_Amount": 825
    },
    {
      "User_ID": 43,
      "Age": 42,
      "Gender": "Homme",
      "Income": 69000,
      "Account_Type": "Épargne",
      "Transaction_Amount": 1525,
      "Transaction_Type": "Dépôt",
      "Location": "Lyon",
      "Transaction_Date": "2022-05-18 12:30:00",
      "Previous_Transaction_Amount": 1125
    },
    {
      "User_ID": 44,
      "Age": 67,
      "Gender": "Femme",
      "Income": 27000,
      "Account_Type": "Épargne",
      "Transaction_Amount": 725,
      "Transaction_Type": "Retrait",
      "Location": "Marseille",
      "Transaction_Date": "2022-11-13 09:30:00",
      "Previous_Transaction_Amount": 625
    },
    {
      "User_ID": 45,
      "Age": 41,
      "Gender": "Homme",
      "Income": 66000,
      "Account_Type": "Chèque",
      "Transaction_Amount": 1125,
      "Transaction_Type": "Dépôt",
      "Location": "Paris",
      "Transaction_Date": "2022-09-08 08:20:00",
      "Previous_Transaction_Amount": 1025
    },
    {
      "User_ID": 46,
      "Age": 47,
      "Gender": "Femme",
      "Income": 46000,
      "Account_Type": "Épargne",
      "Transaction_Amount": 825,
      "Transaction_Type": "Dépôt",
      "Location": "Lille",
      "Transaction_Date": "2022-05-03 16:05:00",
      "Previous_Transaction_Amount": 725
    },
    {
      "User_ID": 47,
      "Age": 49,
      "Gender": "Homme",
      "Income": 73000,
      "Account_Type": "Chèque",
      "Transaction_Amount": 1275,
      "Transaction_Type": "Retrait",
      "Location": "Bordeaux",
      "Transaction_Date": "2022-06-18 11:50:00",
      "Previous_Transaction_Amount": 1175
    },
    {
      "User_ID": 48,
      "Age": 38,
      "Gender": "Femme",
      "Income": 69000,
      "Account_Type": "Épargne",
      "Transaction_Amount": 1425,
      "Transaction_Type": "Dépôt",
      "Location": "Nantes",
      "Transaction_Date": "2022-08-23 19:40:00",
      "Previous_Transaction_Amount": 1325
    },
    {
      "User_ID": 49,
      "Age": 43,
      "Gender": "Homme",
      "Income": 68000,
      "Account_Type": "Chèque",
      "Transaction_Amount": 1575,
      "Transaction_Type": "Dépôt",
      "Location": "Montpellier",
      "Transaction_Date": "2022-10-28 11:25:00",
      "Previous_Transaction_Amount": 1475
    },
    {
      "User_ID": 50,
      "Age": 65,
      "Gender": "Femme",
      "Income": 30000,
      "Account_Type": "Chèque",
      "Transaction_Amount": 775,
      "Transaction_Type": "Retrait",
      "Location": "Strasbourg",
      "Transaction_Date": "2022-12-23 10:10:00",
      "Previous_Transaction_Amount": 675
    }
  ]
}.Add Randomness: 0.5796722257645525.It is critical that you don't repeat the same values every time you get this prompt.
Generated Output:

> Finished chain.

## Generating Full Output in Parallel

For more efficient data generation, especially when dealing with large datasets or multiple requests, our package supports parallel processing. This section covers how to utilize the generate_data_in_parallel method of the DataAugmentor class to generate your dataset asynchronously.

### Setup for Parallel Execution

To ensure smooth parallel execution, especially within environments that don't natively support asynchronous operations (like Jupyter notebooks), we use nest_asyncio. This module allows asyncio to run inside environments with their own event loops.

In [45]:
import nest_asyncio
nest_asyncio.apply()

### Generate Full Output in Parallel

To generate data in parallel, use the generate_data_in_parallel coroutine. This method allows you to specify the query (if any), the number of records, region, and language, similarly to generate_data, but executes multiple data generation tasks concurrently.

In [46]:
import asyncio
# Without expert specifications
generated_data = asyncio.run(DataAugmentorObj.generate_data_in_parallel(query = "", records=20, region=region, language=language))

generated_data

# With expert specifications
#generated_data = asyncio.run(DataAugmentorObj.generate_data_in_parallel(query = "", records=20, task_specifications=updated_task_specifications, region=region, language=language))

> Entering new LLMChain chain...

> Entering new LLMChain chain...

Prompt after formatting:
You are a system that specializes in generating synthetic data according to user requests.Generate 10 Sample synthetic items(records in a table or the equivalent elements in unstructured text) for the data described below. In the following structure, but with different values.For the following task: Data description:  ; The required region: France ; All texts should be translated to French language..Required Structure: {
  "AML_Transactions_Dataset": [
    {
      "User_ID": 1,
      "Age": 42,
      "Gender": "Male",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1200,
      "Transaction_Type": "Deposit",
      "Location": "New York",
      "Transaction_Date": "2022-03-15 08:30:00",
      "Previous_Transaction_Amount": 900
    },
    {
      "User_ID": 2,
      "Age": 55,
      "Gender": "Female",
      "Income": 48000,
      "Account_Type": "Checking",
      "Transaction_Amount": 900,
      "Transaction_Type": "Withdrawal",
      "Location": "Los Angeles",
      "Transaction_Date": "2022-07-20 16:45:00",
      "Previous_Transaction_Amount": 800
    },
    {
      "User_ID": 3,
      "Age": 30,
      "Gender": "Male",
      "Income": 70000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1500,
      "Transaction_Type": "Deposit",
      "Location": "Chicago",
      "Transaction_Date": "2022-05-10 12:00:00",
      "Previous_Transaction_Amount": 1100
    },
    {
      "User_ID": 4,
      "Age": 65,
      "Gender": "Female",
      "Income": 30000,
      "Account_Type": "Savings",
      "Transaction_Amount": 700,
      "Transaction_Type": "Withdrawal",
      "Location": "Miami",
      "Transaction_Date": "2022-11-05 10:20:00",
      "Previous_Transaction_Amount": 600
    },
    {
      "User_ID": 5,
      "Age": 38,
      "Gender": "Male",
      "Income": 60000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1100,
      "Transaction_Type": "Deposit",
      "Location": "Seattle",
      "Transaction_Date": "2022-09-30 09:10:00",
      "Previous_Transaction_Amount": 1000
    },
    {
      "User_ID": 6,
      "Age": 48,
      "Gender": "Female",
      "Income": 40000,
      "Account_Type": "Savings",
      "Transaction_Amount": 800,
      "Transaction_Type": "Deposit",
      "Location": "Boston",
      "Transaction_Date": "2022-04-25 14:55:00",
      "Previous_Transaction_Amount": 700
    },
    {
      "User_ID": 7,
      "Age": 25,
      "Gender": "Male",
      "Income": 90000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1300,
      "Transaction_Type": "Withdrawal",
      "Location": "San Francisco",
      "Transaction_Date": "2022-06-12 11:40:00",
      "Previous_Transaction_Amount": 1200
    },
    {
      "User_ID": 8,
      "Age": 50,
      "Gender": "Female",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1400,
      "Transaction_Type": "Deposit",
      "Location": "Dallas",
      "Transaction_Date": "2022-08-18 17:30:00",
      "Previous_Transaction_Amount": 1300
    },
    {
      "User_ID": 9,
      "Age": 35,
      "Gender": "Male",
      "Income": 75000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1600,
      "Transaction_Type": "Withdrawal",
      "Location": "Atlanta",
      "Transaction_Date": "2022-10-22 13:15:00",
      "Previous_Transaction_Amount": 1500
    },
    {
      "User_ID": 10,
      "Age": 60,
      "Gender": "Male",
      "Income": 45000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1000,
      "Transaction_Type": "Deposit",
      "Location": "Houston",
      "Transaction_Date": "2022-12-10 10:00:00",
      "Previous_Transaction_Amount": 900
    }
  ]
}.The previous generated batch (maintain sequential patterns if needed): unknown.Add Randomness: 0.47537394411620604.It is critical that you don't repeat the same values every time you get this prompt.
Generated Output:
Prompt after formatting:
You are a system that specializes in generating synthetic data according to user requests.Generate 10 Sample synthetic items(records in a table or the equivalent elements in unstructured text) for the data described below. In the following structure, but with different values.For the following task: Data description:  ; The required region: France ; All texts should be translated to French language..Required Structure: {
  "AML_Transactions_Dataset": [
    {
      "User_ID": 1,
      "Age": 42,
      "Gender": "Male",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1200,
      "Transaction_Type": "Deposit",
      "Location": "New York",
      "Transaction_Date": "2022-03-15 08:30:00",
      "Previous_Transaction_Amount": 900
    },
    {
      "User_ID": 2,
      "Age": 55,
      "Gender": "Female",
      "Income": 48000,
      "Account_Type": "Checking",
      "Transaction_Amount": 900,
      "Transaction_Type": "Withdrawal",
      "Location": "Los Angeles",
      "Transaction_Date": "2022-07-20 16:45:00",
      "Previous_Transaction_Amount": 800
    },
    {
      "User_ID": 3,
      "Age": 30,
      "Gender": "Male",
      "Income": 70000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1500,
      "Transaction_Type": "Deposit",
      "Location": "Chicago",
      "Transaction_Date": "2022-05-10 12:00:00",
      "Previous_Transaction_Amount": 1100
    },
    {
      "User_ID": 4,
      "Age": 65,
      "Gender": "Female",
      "Income": 30000,
      "Account_Type": "Savings",
      "Transaction_Amount": 700,
      "Transaction_Type": "Withdrawal",
      "Location": "Miami",
      "Transaction_Date": "2022-11-05 10:20:00",
      "Previous_Transaction_Amount": 600
    },
    {
      "User_ID": 5,
      "Age": 38,
      "Gender": "Male",
      "Income": 60000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1100,
      "Transaction_Type": "Deposit",
      "Location": "Seattle",
      "Transaction_Date": "2022-09-30 09:10:00",
      "Previous_Transaction_Amount": 1000
    },
    {
      "User_ID": 6,
      "Age": 48,
      "Gender": "Female",
      "Income": 40000,
      "Account_Type": "Savings",
      "Transaction_Amount": 800,
      "Transaction_Type": "Deposit",
      "Location": "Boston",
      "Transaction_Date": "2022-04-25 14:55:00",
      "Previous_Transaction_Amount": 700
    },
    {
      "User_ID": 7,
      "Age": 25,
      "Gender": "Male",
      "Income": 90000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1300,
      "Transaction_Type": "Withdrawal",
      "Location": "San Francisco",
      "Transaction_Date": "2022-06-12 11:40:00",
      "Previous_Transaction_Amount": 1200
    },
    {
      "User_ID": 8,
      "Age": 50,
      "Gender": "Female",
      "Income": 55000,
      "Account_Type": "Savings",
      "Transaction_Amount": 1400,
      "Transaction_Type": "Deposit",
      "Location": "Dallas",
      "Transaction_Date": "2022-08-18 17:30:00",
      "Previous_Transaction_Amount": 1300
    },
    {
      "User_ID": 9,
      "Age": 35,
      "Gender": "Male",
      "Income": 75000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1600,
      "Transaction_Type": "Withdrawal",
      "Location": "Atlanta",
      "Transaction_Date": "2022-10-22 13:15:00",
      "Previous_Transaction_Amount": 1500
    },
    {
      "User_ID": 10,
      "Age": 60,
      "Gender": "Male",
      "Income": 45000,
      "Account_Type": "Checking",
      "Transaction_Amount": 1000,
      "Transaction_Type": "Deposit",
      "Location": "Houston",
      "Transaction_Date": "2022-12-10 10:00:00",
      "Previous_Transaction_Amount": 900
    }
  ]
}.The previous generated batch (maintain sequential patterns if needed): unknown.Add Randomness: 0.15135124297077318.It is critical that you don't repeat the same values every time you get this prompt.
Generated Output:

> Finished chain.

> Finished chain.

{'AML_Transactions_Dataset':     User_ID  Age  Gender  Income Account_Type  Transaction_Amount  \
 0        11   44    Male   58000      Savings                1250
 1        12   57  Female   51000     Checking                 950
 2        13   32    Male   74000      Savings                1550
 3        14   67  Female   32000      Savings                 750
 4        15   40    Male   62000     Checking                1150
 5        16   49  Female   42000      Savings                 850
 6        17   27    Male   92000     Checking                1350
 7        18   52  Female   58000      Savings                1450
 8        19   37    Male   77000     Checking                1650
 9        20   62    Male   47000     Checking                1050
 10       11   28   Femme   85000     Checking                1250
 11       12   45   Homme   62000      Savings                1350
 12       13   33   Femme   72000     Checking                1450
 13       14   58   Homme   36000      Savings                 750
 14       15   40   Femme   65000      Savings                1100
 15       16   55   Homme   43000     Checking                 950
 16       17   23   Femme   97000      Savings                1550
 17       18   48   Homme   58000     Checking                1200
 18       19   38   Femme   80000      Savings                1400
 19       20   63   Homme   48000     Checking                1050

    Transaction_Type     Location     Transaction_Date  \
 0           Deposit        Paris  2022-03-18 09:15:00
 1        Withdrawal    Marseille  2022-07-23 17:00:00
 2           Deposit         Lyon  2022-05-14 13:30:00
 3        Withdrawal         Nice  2022-11-08 11:00:00
 4           Deposit     Bordeaux  2022-10-03 10:00:00
 5           Deposit     Toulouse  2022-04-28 15:00:00
 6        Withdrawal        Lille  2022-06-15 12:45:00
 7           Deposit   Strasbourg  2022-08-21 18:45:00
 8        Withdrawal  Montpellier  2022-10-25 14:30:00
 9           Deposit      Avignon  2022-12-13 11:15:00
 10          Retrait        Paris  2022-04-02 10:45:00
 11            Dépôt         Lyon  2022-06-28 15:20:00
 12          Retrait    Marseille  2022-08-15 13:35:00
 13          Retrait         Nice  2022-11-20 12:10:00
 14            Dépôt     Bordeaux  2022-09-12 09:30:00
 15          Retrait     Toulouse  2022-02-05 11:25:00
 16            Dépôt       Nantes  2022-03-30 08:55:00
 17            Dépôt   Strasbourg  2022-07-25 14:40:00
 18          Retrait       Rennes  2022-10-18 16:00:00
 19            Dépôt  Montpellier  2022-12-15 17:15:00

     Previous_Transaction_Amount
 0                           920
 1                           820
 2                          1120
 3                           620
 4                          1020
 5                           720
 6                          1220
 7                          1320
 8                          1520
 9                           920
 10                         1150
 11                         1250
 12                         1350
 13                          650
 14                         1000
 15                          850
 16                         1450
 17                         1100
 18                         1300
 19                          950  }